tasks:
    - name: dx
      init: |
          npm install -g npm@10.1.0
          npm install -g bun
          git config lfs.https://github.com/beingofexistence/dx.git/info/lfs.locksverify false
          cd apps/www && bun install && bun run build
      command: |
          bun run dev
        #   docker run -it --init -p 3000:3000 -v "$(pwd):/home/workspace:cached" 7c0e19dd4517
        #   docker pull gitpod/openvscode-server
    # - name: nextui
    #   init: |
    #       cd nextui && pnpm install
    #   command: |
    #       cd apps/docs pnpm run dev
    # - name: nextui
    #   init: |
    #       cd nextui && pnpm install
    #   command: |
    #       cd apps/docs pnpm run dev
    # - name: dxcode
    #   init: |
    #       bash dxcode.sh
    #       cd openvscode-server-redesignded && yarn run installation && yarn run run-app && cd ..
    # - name: Nextui
    #   init: |
    #       cd inspirations && cd www && pnpm install
    #       pnpm run build
    #   command: |
    #       pnpm run dev
    # - name: terminalflow-typescript
    #   init: |
    #       cd packages && cd terminalflow && pnpm install
    #       pnpm run typescript
    #   command: |
    #       pnpm run dev
    # - name: terminalflow
    #   init: |
    #       cd packages && cd terminalflow && pnpm install
    #   command: |
    #       pnpm run dev
    # - name: tailwindcss-documentation
    #   init: |
    #       cd inspirations &&
    #       git clone https://github.com/beingofexistence/tailwindcss-documentation.git &&
    #       cd tailwindcss-documentation &&
    #       rm -rf .git
    #   command: |
    #       yarn install &&
    #       yarn run build
    # - name: nextui
    #   init: |
    #       cd inspirations &&
    #       git clone https://github.com/beingofexistence/nextui.git &&
    #       cd nextui &&
    #       rm -rf .git
    # - name: material-ui
    #   init: |
    #       cd inspirations &&
    #       git clone https://github.com/beingofexistence/material-ui.git &&
    #       cd material-ui &&
    #       rm -rf .git
    #   command: |
    #       yarn install
    # - name: nextjs
    #   init: |
    #       cd inspirations &&
    #       git clone https://github.com/vercel/next.js.git &&
    #       cd next.js &&
    #       rm -rf .git
    # - name: WorkSpace
    #   init: |
    #       pnpm install
    #       pnpm run build
    # - name: Terminal
    #   init: |









