const axios = require("axios")
let url = "https://www.passportjs.org/packages/passport-facebook" // Replace with the URL of the website you want to scrape
let passports, passport_github_repository, regex, matcher


passports = [
  { title: "facebook" },
  { title: "twitter" },
  { title: "auth" },
  { title: "jwt" },
  { title: "local" },
  { title: "oauth" },
  { title: "oauth" },
  { title: "saml" },
  { title: "oauth" },
  { title: "http" },
  { title: "custom" },
  { title: "github" },
  { title: "github" },
  { title: "microsoft" },
  { title: "apple" },
  { title: "anonymous" },
  { title: "gitlab" },
  { title: "openidconnect" },
  { title: "totp" },
  { title: "ldapauth" },
  { title: "ping" },
  { title: "line" },
  { title: "cookie" },
  { title: "slack" },
  { title: "forcedotcom" },
  { title: "steam" },
  { title: "discord" },
  { title: "openid" },
  { title: "instagram" },
  { title: "kakao" },
  { title: "google" },
  { title: "docusign" },
  { title: "amazon" },
  { title: "activedirectory" },
  { title: "vkontakte" },
  { title: "zendesk" },
  { title: "appleid" },
  { title: "magic" },
  { title: "linkedin" },
  { title: "naver" },
  { title: "spotify" },
  { title: "json" },
  { title: "intercom" },
  { title: "accesstoken" },
  { title: "orcid" },
  { title: "shopify" },
  { title: "asana" },
  { title: "localapikey" },
  { title: "windowslive" },
  { title: "hash" },
  { title: "pinterest" },
  { title: "mail" },
  { title: "windowsauth" },
  { title: "stripe" },
  { title: "deezer" },
  { title: "outlook" },
  { title: "nest" },
  { title: "wechat" },
  { title: "bluemix" },
  { title: "odnoklassniki" },
  { title: "twitch" },
  { title: "yandex" },
  { title: "mailchimp" },
  { title: "lti" },
  { title: "xero" },
  { title: "snapchat" },
  { title: "trakt" },
  { title: "reddit" },
  { title: "httpapikey" },
  { title: "xing" },
  { title: "bnet" },
  { title: "tumblr" },
  { title: "trello" },
  { title: "box" },
  { title: "echosign" },
  { title: "web" },
  { title: "headhunter" },
  { title: "bitbucket" },
  { title: "vso" },
  { title: "yammer" },
  { title: "pocket" },
  { title: "strava" },
  { title: "meetup" },
  { title: "outlook" },
  { title: "authtkt" },
  { title: "ethereum" },
  { title: "telegram" },
  { title: "bitly" },
  { title: "lastfm" },
  { title: "podio" },
  { title: "signals" },
  { title: "hubspot" },
  { title: "foursquare" },
  { title: "smartsheet" },
  { title: "mixcloud" },
  { title: "appfigures" },
  { title: "fitbit" },
  { title: "arcgis" },
  { title: "publickey" },
  { title: "imgur" },
  { title: "qq" },
  { title: "dropbox" },
  { title: "soundcloud" },
  { title: "flickr" },
  { title: "smartthings" },
  { title: "onshape" },
  { title: "hmac" },
  { title: "wordpress" },
  { title: "citrix" },
  { title: "mercadolibre" },
  { title: "sharepoint" },
  { title: "coinbase" },
  { title: "tequila" },
  { title: "sheknows" },
  { title: "raven" },
  { title: "jawbone" },
  { title: "verify" },
  { title: "draugiem" },
  { title: "dailymotion" },
  { title: "weixin" },
  { title: "paypal" },
  { title: "yahoo" },
  { title: "deviantart" },
  { title: "bufferapp" },
  { title: "dribbble" },
  { title: "maltio" },
  { title: "gitlab" },
  { title: "ghost" },
  { title: "youtube" },
  { title: "vimeo" },
  { title: "dataporten" },
  { title: "drupal" },
  { title: "hawk" },
  { title: "mastodon" },
  { title: "campaignmonitor" },
  { title: "constantcontact" },
  { title: "line" },
  { title: "weibo" },
  { title: "tradier" },
  { title: "yj" },
  { title: "digitalocean" },
  { title: "daccount" },
  { title: "mailru" },
  { title: "stormpath" },
  { title: "familysearch" },
  { title: "lds" },
  { title: "oneauth" },
  { title: "citrix" },
  { title: "jive" },
  { title: "uwshib" },
  { title: "goodreads" },
  { title: "cloudfoundry" },
  { title: "intuit" },
  { title: "idn" },
  { title: "opentoken" },
  { title: "abakus" },
  { title: "eve" },
  { title: "basecrm" },
  { title: "dailycred" },
  { title: "disqus" },
  { title: "ionisx" },
  { title: "surveymonkey" },
  { title: "tidal" },
  { title: "tiendanube" },
  { title: "userapp" },
  { title: "eveonline" },
  { title: "gumroad" },
  { title: "civic" },
  { title: "stanford" },
  { title: "square" },
  { title: "waad" },
  { title: "indieauth" },
  { title: "nexon" },
  { title: "iucas" },
  { title: "ustream" },
  { title: "basecamp" },
  { title: "borchk" },
  { title: "namely" },
  { title: "thingiverse" },
  { title: "ufshib" },
  { title: "twitchtv" },
  { title: "keystone" },
  { title: "persona" },
  { title: "veritone" },
  { title: "workwell" },
  { title: "andme" },
  { title: "ldsauth" },
  { title: "mymlh" },
  { title: "stackexchange" },
  { title: "clevercloud" },
  { title: "hackid" },
  { title: "identityua" },
  { title: "ssqsignon" },
  { title: "ehealth" },
  { title: "gowalla" },
  { title: "groupme" },
  { title: "nextengine" },
  { title: "signature" },
  { title: "automatic" },
  { title: "dd" },
  { title: "delivery" },
  { title: "exact" },
  { title: "monarch" },
  { title: "octoblu" },
  { title: "privakey" },
  { title: "sitegate" },
  { title: "thegrid" },
  { title: "weibonew" },
  { title: "runkeeper" },
  { title: "hotp" },
  { title: "openstreetmap" },
  { title: "descope" },
  { title: "rakuten" },
  { title: "unilogin" },
  { title: "assembla" },
  { title: "baidu" },
  { title: "lyft" },
  { title: "ses" },
  { title: "everyplay" },
  { title: "predix" },
  { title: "supinfo" },
  { title: "trademe" },
  { title: "beatsmusic" },
  { title: "edmodo" },
  { title: "feedly" },
  { title: "freshbooks" },
  { title: "justintv" },
  { title: "metocean" },
  { title: "oauth" },
  { title: "pnoi" },
  { title: "sharefile" },
  { title: "stocktwits" },
  { title: "wink" },
  { title: "anyexercise" },
  { title: "approveapi" },
  { title: "apptrack" },
  { title: "artycles" },
  { title: "assetorium" },
  { title: "authtoken" },
  { title: "coola" },
  { title: "crudr" },
  { title: "fanfou" },
  { title: "fido" },
  { title: "honeywell" },
  { title: "kerberos" },
  { title: "kuali" },
  { title: "latch" },
  { title: "learningstudio" },
  { title: "lims" },
  { title: "meituan" },
  { title: "nationbuilder" },
  { title: "nuwe" },
  { title: "passwordless" },
  { title: "payco" },
  { title: "redgate" },
  { title: "rightsignature" },
  { title: "scarecrow" },
  { title: "singly" },
  { title: "thinkful" },
  { title: "tibbr" },
  { title: "versionone" },
  { title: "wargaming" },
  { title: "applywithlinkedin" },
  { title: "browserid" },
  { title: "zero" },
  { title: "tqq" },
  { title: "px" },
  { title: "evernote" },
  { title: "pixiv" },
  { title: "venmo" },
  { title: "parse" },
  { title: "tmobileid" },
  { title: "dwolla" },
  { title: "sqrl" },
  { title: "withings" },
  { title: "angellist" },
  { title: "humanapi" },
  { title: "rdio" },
  { title: "drchrono" },
  { title: "renren" },
  { title: "geoloqi" },
  { title: "readability" },
  { title: "smugmug" },
  { title: "statusnet" },
  { title: "suzuri" },
  { title: "tripit" },
  { title: "appdotnet" },
  { title: "behance" },
  { title: "eyeem" },
  { title: "fellowshipone" },
  { title: "ifmosso" },
  { title: "myusa" },
  { title: "pop" },
  { title: "replicated" },
  { title: "taobao" },
  { title: "aol" },
  { title: "appc" },
  { title: "authentiq" },
  { title: "bong" },
  { title: "geeklist" },
  { title: "idsus" },
  { title: "misfit" },
  { title: "moves" },
  { title: "netatmo" },
  { title: "nopassword" },
  { title: "nyu" },
  { title: "oschina" },
  { title: "punwave" },
  { title: "stash" },
  { title: "tistory" },
  { title: "untappd" },
  { title: "akera" },
  { title: "andyet" },
  { title: "authic" },
  { title: "authing" },
  { title: "digg" },
  { title: "liondesk" },
  { title: "mentalvein" },
  { title: "mojeid" },
  { title: "netflix" },
  { title: "ohloh" },
  { title: "picplz" },
  { title: "playlyfe" },
  { title: "proz" },
  { title: "sense" },
  { title: "slice" },
  { title: "topcoder" },
  { title: "underarmour" },
  { title: "webauthn" },
  { title: "xmpp" },
  { title: "time" },
  { title: "accountkit" },
  { title: "allplayers" },
  { title: "amigame" },
  { title: "animexx" },
  { title: "avalon" },
  { title: "bamboohr" },
  { title: "beatport" },
  { title: "bitauth" },
  { title: "chiiv" },
  { title: "cloudvisio" },
  { title: "comicsgl" },
  { title: "concur" },
  { title: "costlocker" },
  { title: "deskcom" },
  { title: "dice" },
  { title: "distimo" },
  { title: "douban" },
  { title: "dowjones" },
  { title: "earthmaps" },
  { title: "eloqua" },
  { title: "flic" },
  { title: "frontwinner" },
  { title: "globelabs" },
  { title: "gocollab" },
  { title: "hackerverse" },
  { title: "infotjenester" },
  { title: "ktt" },
  { title: "makerpass" },
  { title: "mapmyfitness" },
  { title: "meday" },
  { title: "medoauth" },
  { title: "mixi" },
  { title: "nate" },
  { title: "nuclearhub" },
  { title: "odesk" },
  { title: "oneprofile" },
  { title: "oneuser" },
  { title: "onscribe" },
  { title: "oz" },
  { title: "passprint" },
  { title: "polkaspots" },
  { title: "redbooth" },
  { title: "rescour" },
  { title: "sbhs" },
  { title: "slidefuse" },
  { title: "socius" },
  { title: "taobao" },
  { title: "teamsnap" },
  { title: "torchlite" },
  { title: "txssc" },
  { title: "uber" },
  { title: "ubersmith" },
  { title: "ucoz" },
  { title: "ultraauth" },
  { title: "unichar" },
  { title: "urlship" },
  { title: "uservoice" },
  { title: "vivokey" },
  { title: "wauth" },
  { title: "wanliu" },
  { title: "wevision" },
  { title: "zengine" },
  { title: "faceit" },
  { title: "npm" },
  { title: "cloudup" },
  { title: "webmaker" },
  { title: "gitbook" },
  { title: "headerapikey" },
  { title: "heroku" },
  { title: "infusionsoft" },
  { title: "instantfa" },
  { title: "monzo" },
  { title: "phantauth" },
  { title: "pocket" },
  { title: "sina" },
  { title: "wca" },
  { title: "http-bearer" },
  { title: "google-oauth" },
  { title: "google-oauth" },
  { title: "azure-ad" },
  { title: "google-oauth" },
  { title: "google-oauth" },
  { title: "bitbucket-oauth" },
  { title: "okta-oauth" },
  { title: "linkedin-oauth" },
  { title: "atlassian-oauth" },
  { title: "unique-token" },
  { title: "auth-token" },
  { title: "magic-login" },
  { title: "slack-oauth" },
  { title: "google-oidc" },
  { title: "trusted-header" },
  { title: "fa-totp" },
  { title: "client-cert" },
  { title: "wsfed-saml" },
  { title: "remember-me" },
  { title: "jwt-cookiecombo" },
  { title: "youtube-v" },
  { title: "magic-link" },
  { title: "dropbox-oauth" },
  { title: "line-auth" },
  { title: "http-oauth" },
  { title: "azure-oauth" },
  { title: "ping-oauth" },
  { title: "ibmid-oauth" },
  { title: "bitbucket-oauth" },
  { title: "predix-oauth" },
  { title: "anonym-uuid" },
  { title: "fido-webauthn" },
  { title: "ok-strategy" },
  { title: "google-plus" },
  { title: "heroku-addon" },
  { title: "local-token" },
  { title: "json-custom" },
  { title: "did-auth" },
  { title: "fitbit-oauth" },
  { title: "adobe-oauth" },
  { title: "ethereum-siwe" },
  { title: "strava-oauth" },
  { title: "yahoo-oauth" },
  { title: "meetup-oauth" },
  { title: "oauth-meetup" },
  { title: "client-certificate" },
  { title: "zoho-crm" },
  { title: "cisco-spark" },
  { title: "local-htpasswd" },
  { title: "eventbrite-oauth" },
  { title: "stack-exchange" },
  { title: "intuit-oauth" },
  { title: "office-oauth" },
  { title: "lnurl-auth" },
  { title: "daum-oauth" },
  { title: "vk-strategy" },
  { title: "weixin-enterprise" },
  { title: "saml-too" },
  { title: "paypal-oauth" },
  { title: "mondo-oauth" },
  { title: "rdio-oauth" },
  { title: "lds-connect" },
  { title: "taccounts-oauth" },
  { title: "http-signature" },
  { title: "uber-v" },
  { title: "coursera-oauth" },
  { title: "line-v" },
  { title: "jd-credit" },
  { title: "shutterstock-oauth" },
  { title: "cloudfoundry-openidconnect" },
  { title: "lds-io" },
  { title: "sharepoint-addin" },
  { title: "digital-signature" },
  { title: "wix-app" },
  { title: "dropbox-business" },
  { title: "planningcenter-oauth" },
  { title: "hmac-aws" },
  { title: "weixin-plus" },
  { title: "dapp-web" },
  { title: "wechat-work" },
  { title: "nus-openid" },
  { title: "chalkable-oauth" },
  { title: "heroku-sso" },
  { title: "acuity-oauth" },
  { title: "azure-store" },
  { title: "brightspace-auth" },
  { title: "dedicated-bluemix" },
  { title: "edmodo-api" },
  { title: "voice-it" },
  { title: "addressix-oauth" },
  { title: "atlassian-crowd" },
  { title: "att-alpha" },
  { title: "coding-oauth" },
  { title: "eipsk-strategy" },
  { title: "encored-enertalk" },
  { title: "estimote-cloud" },
  { title: "mediawiki-oauth" },
  { title: "open-humans" },
  { title: "ppige-npdc" },
  { title: "product-hunt" },
  { title: "renren-new" },
  { title: "restogram-oauth" },
  { title: "wechat-auth" },
  { title: "atlassian-connect" },
  { title: "fido-nojwk" },
  { title: "windowslive-contacts" },
]

passports.map((passports) => {
    axios
      .get(`https://www.passportjs.org/packages/passport-${passports.title}`)
      .then((response) => {
        const html = response.data
        matcher =
          "From This Sentence I have to select this(Yes!!!,You Selected The Right Thing)"
        preregex = html.match(/.url. href..https...github.com.\w+.\w+-\w+/g)

        passport_github_repository = `git clone ${preregex}`;
        console.log(passport_github_repository);
      })
      .catch((error) => {
        console.error("Error fetching the page:", error)
      })
})

// for (let i = 0; i < passports.length; i++) {
//   axios
//   .get(`https://www.passportjs.org/packages/passport-${passports.title}`)
//   .then((response) => {
//     const html = response.data
//     matcher =
//       "From This Sentence I have to select this(Yes!!!,You Selected The Right Thing)"
//     preregex = html.match(/.url. href..https...github.com.\w+.\w+-\w+/g)

//     passport_github_repository = `git clone ${preregex}`;
//     console.log(passport_github_repository);
//   })
//   .catch((error) => {
//     console.error("Error fetching the page:", error)
//   })
// }

  // axios.get(url)
  // .then(response => {
  //   const html = response.data; // HTML content of the page
  //   regex = html.match(/\s\W""https:..github.com.beingofexistence.dx""/g);

  //   // Now you can parse and extract data from the HTML
  //   passport_github_repository = `git clone ${regex}`;
  //   console.log(passport_github_repository);
  // })
  // .catch(error => {
  //   console.error('Error fetching the page:', error);
  // });


// axios.get(url)
// .then(response => {

//   const html = response.data; // HTML content of the page
//   matcher = "From This Sentence I have to select this(Yes!!!,You Selected The Right Thing)"
//   preregex = html.match(/.url. href..https...github.com.\w+.\w+-\w+/g);
//   // regex = preregex.replace(/https/i,'/https...github.com.\w+.\w+-\w+/g');
//   // const str = '.url. href..https...github.com.\w+.\w+-\w+';
//   // regex = html.match(/\s\W"https:..github.com.\w+.\w+-\w+"/g);

//   // Now you can parse and extract data from the HTML
//   passport_github_repository = `git clone ${preregex}`;
//   console.log(passport_github_repository);
// })
// .catch(error => {
//   console.error('Error fetching the page:', error);
// });
