import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../../ui/globals.css'
import Navbar from '@/component/navbar'
import Footer from '@/component/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Navbar />
        {children}
        <Footer />
      
      </body>
    </html>
  )
}
