import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='2xs:bg-rose-500 xs:bg-gray-900 sm:bg-zinc-900 md:bg-lime-400 lg:bg-emerald-500 xl:bg-cyan-500 2xl:bg-violet-800'>{children}</body>
    </html>
  )
}
